import { jsPDF } from 'jspdf'

export const exportToPDF = (itinerary) => {
  if (!itinerary) return

  const currencySymbol = itinerary.currency_symbol || '$'
  const doc = new jsPDF()
  let y = 20

  // Header Title
  doc.setFontSize(20)
  doc.setTextColor(2, 132, 199) // Sky Blue
  doc.text(itinerary.title || 'WanderSync Travel Itinerary', 14, y)

  y += 10
  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.text(`Destination: ${itinerary.destination} | Dates: ${itinerary.start_date} to ${itinerary.end_date}`, 14, y)

  y += 6
  doc.text(`Total Budget: ${currencySymbol}${itinerary.total_estimated_cost} | Share Token: ${itinerary.share_token}`, 14, y)

  y += 10
  doc.setLineWidth(0.5)
  doc.setDrawColor(226, 232, 240)
  doc.line(14, y, 196, y)
  y += 10

  // Days & Activities
  const days = itinerary.days || []
  days.forEach((day) => {
    if (y > 260) {
      doc.addPage()
      y = 20
    }

    doc.setFontSize(14)
    doc.setTextColor(15, 23, 42)
    doc.text(`Day ${day.day_number}: ${day.title || ''} (${day.date || ''})`, 14, y)
    y += 6

    if (day.weather) {
      doc.setFontSize(9)
      doc.setTextColor(71, 85, 105)
      doc.text(`Weather: ${day.weather.condition || 'Mild'} (${day.weather.temp_max_c}°C / ${day.weather.temp_min_c}°C)`, 14, y)
      y += 6
    }

    const activities = day.activities || []
    activities.forEach((act) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }

      doc.setFontSize(10)
      doc.setTextColor(30, 41, 59)
      const timeStr = act.start_time ? `[${act.start_time} - ${act.end_time}] ` : ''
      doc.text(`• ${timeStr}${act.title} - ${currencySymbol}${act.cost_estimate || 0}`, 18, y)
      y += 5

      if (act.description) {
        doc.setFontSize(8.5)
        doc.setTextColor(100, 116, 139)
        const splitDesc = doc.splitTextToSize(act.description, 170)
        doc.text(splitDesc, 22, y)
        y += (splitDesc.length * 4) + 2
      }
    })

    y += 6
  })

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('Generated by WanderSync Generative AI Travel Planner (100% Free & Open Source)', 14, 285)

  doc.save(`${itinerary.destination.replace(/[^a-z0-9]/gi, '_')}_Itinerary.pdf`)
}

export const exportToICS = (itinerary) => {
  if (!itinerary) return

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//WanderSync AI Travel Planner//EN',
    'CALSCALE:GREGORIAN'
  ]

  const days = itinerary.days || []
  days.forEach((day) => {
    const activities = day.activities || []
    activities.forEach((act, idx) => {
      const dateClean = (day.date || '20261010').replace(/-/g, '')
      const startClean = (act.start_time || '10:00').replace(':', '') + '00'
      const endClean = (act.end_time || '11:30').replace(':', '') + '00'

      icsContent.push(
        'BEGIN:VEVENT',
        `SUMMARY:${act.title} (${itinerary.destination})`,
        `DESCRIPTION:${(act.description || '').replace(/\n/g, ' ')}`,
        `LOCATION:${act.address || itinerary.destination}`,
        `DTSTART:${dateClean}T${startClean}`,
        `DTEND:${dateClean}T${endClean}`,
        `UID:${itinerary.id}-${day.day_number}-${idx}@wandersync.ai`,
        'END:VEVENT'
      )
    })
  })

  icsContent.push('END:VCALENDAR')

  const blob = new Blob([icsContent.join('\n')], { type: 'text/calendar;charset=utf-8' })
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.setAttribute('download', `${itinerary.destination.replace(/[^a-z0-9]/gi, '_')}_Calendar.ics`)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}